name: GitOps

###
# GitOps - automatic infrastructure management GitHub Action
#
# See https://docs.nubesgen.com/gitops/gitops-quick-start/
# for more information about using GitOps with NubesGen.
###

on:
  push:
    branches:
      - 'env-*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    outputs:
      application_name: ${{ steps.infrastructure-deployment.outputs.application_name }}
      application_url: ${{ steps.infrastructure-deployment.outputs.application_url }}
      resource_group: ${{ steps.infrastructure-deployment.outputs.resource_group }}
      container_registry_name: ${{ steps.infrastructure-deployment.outputs.container_registry_name }}
    steps:
      - name: Apply Terraform configuration
        id: infrastructure-deployment
        uses: microsoft/nubesgen-actions/gitops-apply-terraform@v0.8.0
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          tf_storage_account: ${{ secrets.TF_STORAGE_ACCOUNT }}
      - name: Build a Micronaut docker image project using Maven
        uses: microsoft/nubesgen-actions/gitops-build-java-maven@v0.8.0
        with:
          build_command: mvn clean package -Dpackaging=docker -Djib.to.image=${{ steps.infrastructure-deployment.outputs.container_registry_name }}.azurecr.io/${{ steps.infrastructure-deployment.outputs.application_name }}/${{ steps.infrastructure-deployment.outputs.application_name }}:${{ github.sha }}
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Push to Azure Container Registry
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          az acr login -n ${{ steps.infrastructure-deployment.outputs.container_registry_name }}.azurecr.io
          docker push ${{ steps.infrastructure-deployment.outputs.container_registry_name }}.azurecr.io/${{ steps.infrastructure-deployment.outputs.application_name }}/${{ steps.infrastructure-deployment.outputs.application_name }}:${{ github.sha }}
        shell: bash
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.infrastructure-deployment.outputs.application_name }}
          images: '${{ steps.infrastructure-deployment.outputs.container_registry_name }}.azurecr.io/${{ steps.infrastructure-deployment.outputs.application_name }}/${{ steps.infrastructure-deployment.outputs.application_name }}:${{ github.sha }}'
  display-information:
    needs: [build-and-deploy]
    runs-on: ubuntu-20.04
    steps:
      - name: Display Azure infrastructure information
        uses: microsoft/nubesgen-actions/gitops-display-information@v0.8.0
        with:
          application_name: ${{ needs.build-and-deploy.outputs.application_name }}
          application_url: ${{ needs.build-and-deploy.outputs.application_url }}
          resource_group: ${{ needs.build-and-deploy.outputs.resource_group }}
